In [1]:
"""
import tkinter as tk
import numpy as np

#Initialize a 100x100 grid with all zeroes
grid_size = 5
maze_grid = np.zeros((grid_size, grid_size))

#Create a tkinter window
window = tk.Tk()
window.title("Maze Obstacle Selector")

cell_size = 10  # Size of each cell

#Create a canvas to display the grid
canvas = tk.Canvas(window, width=grid_size * cell_size, height=grid_size * cell_size)
canvas.pack()

#Function to toggle obstacle (0 -> 1 or 1 -> 0) on click
def toggle_obstacle(event):
    # Get the grid coordinates based on the click location
    x, y = event.x // cell_size, event.y // cell_size
    # Toggle the grid value at that point
    maze_grid[y, x] = 1 if maze_grid[y, x] == 0 else 0
    # Update the visual representation
    draw_grid()

#Function to draw the grid
def draw_grid():
    canvas.delete("all")
    for row in range(grid_size):
        for col in range(grid_size):
            color = "white" if maze_grid[row, col] == 0 else "black"
            canvas.create_rectangle(
                col * cell_size, row * cell_size,
                (col + 1) * cell_size, (row + 1) * cell_size,
                fill=color, outline="gray"
            )

#Bind mouse click to the toggle function
canvas.bind("<Button-1>", toggle_obstacle)

#Draw the initial grid
draw_grid()

#Start the tkinter loop
window.mainloop()
"""

'\nimport tkinter as tk\nimport numpy as np\n\n#Initialize a 100x100 grid with all zeroes\ngrid_size = 5\nmaze_grid = np.zeros((grid_size, grid_size))\n\n#Create a tkinter window\nwindow = tk.Tk()\nwindow.title("Maze Obstacle Selector")\n\ncell_size = 10  # Size of each cell\n\n#Create a canvas to display the grid\ncanvas = tk.Canvas(window, width=grid_size * cell_size, height=grid_size * cell_size)\ncanvas.pack()\n\n#Function to toggle obstacle (0 -> 1 or 1 -> 0) on click\ndef toggle_obstacle(event):\n    # Get the grid coordinates based on the click location\n    x, y = event.x // cell_size, event.y // cell_size\n    # Toggle the grid value at that point\n    maze_grid[y, x] = 1 if maze_grid[y, x] == 0 else 0\n    # Update the visual representation\n    draw_grid()\n\n#Function to draw the grid\ndef draw_grid():\n    canvas.delete("all")\n    for row in range(grid_size):\n        for col in range(grid_size):\n            color = "white" if maze_grid[row, col] == 0 else "black"\n     

In [2]:
import numpy as np
import random

def create_maze(grid_size):    
    grid = np.ones((grid_size, grid_size), dtype=int)

    start_x, start_y = (1, 1)
    # grid[start_x, start_y] = 2

    directions = [(0, 2), (2, 0), (0, -2), (-2, 0)]
    
    def carve(x, y):
        
        random.shuffle(directions)
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 < nx < grid_size and 0 < ny < grid_size and grid[nx, ny] == 1:

                grid[nx, ny] = 0
                grid[x + dx // 2, y + dy // 2] = 0
                carve(nx, ny)

    carve(start_x, start_y)
    
    grid[:, 0] = 0
    #grid[0, :] = 0
   
    return grid

grid_size = 100
    
maze_grid = create_maze(grid_size)

for row in maze_grid:
    print(' '.join(['*' if cell == 1 else '$' if cell == 2 else ' ' for cell in row]))

  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    *                       *       *       *   *           *                                           *       *               *       *                   *               *       *                  
    *   *   * * * * * * *   *   * * *   *   *   *   * * *   *   * * * * * * * * * * * * * * * * * * *   *   *   *   * * * * *   *   *   *   * * * * * * *   *   *   * * * * *   *   *   *   * * * * *  
    *   *   *       *       *       *   *           *       *   *           *           *           *   *   *       *       *       *       *       *       *   *           *   *       *   *       *  
    * * *   *   *   *   * * * * *   *   *   * * * * *   * * *   * * * * *   *   * * *   *   * * *   *   * * * * *   *   *   * * * * * * * * *   * * *   * * *   * * *   *   *   * * * * *   *   * * *  


In [3]:
print(maze_grid)

[[0 1 1 ... 1 1 1]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 1 1 0]
 ...
 [0 0 1 ... 0 1 0]
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]


In [4]:
OBSTACLES = []
for row in range(len(maze_grid)):
    for col in range(len(maze_grid)):
        if maze_grid[row][col] == 1:
            OBSTACLES.append((row,col))
OBSTACLES

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 34),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 48),
 (0, 49),
 (0, 50),
 (0, 51),
 (0, 52),
 (0, 53),
 (0, 54),
 (0, 55),
 (0, 56),
 (0, 57),
 (0, 58),
 (0, 59),
 (0, 60),
 (0, 61),
 (0, 62),
 (0, 63),
 (0, 64),
 (0, 65),
 (0, 66),
 (0, 67),
 (0, 68),
 (0, 69),
 (0, 70),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 74),
 (0, 75),
 (0, 76),
 (0, 77),
 (0, 78),
 (0, 79),
 (0, 80),
 (0, 81),
 (0, 82),
 (0, 83),
 (0, 84),
 (0, 85),
 (0, 86),
 (0, 87),
 (0, 88),
 (0, 89),
 (0, 90),
 (0, 91),
 (0, 92),
 (0, 93),
 (0, 94),
 (0, 95),
 (0, 96),
 (0, 97),
 (0, 98),
 (0, 99),
 (1, 2),
 (1, 14),


In [5]:
GRID_SIZE = 100
START = (0,0)
GOAL = (GRID_SIZE-1,GRID_SIZE-1)
#OBSTACLES = [(0,0),(0,2),(0,4),(1,4),(2,1),(2,2),(3,4),(4,1),(4,2),(4,4)]
ACTIONS = [(-1,0),(0,1),(1,0),(0,-1)]
EPSILON = 0.3
ALPHA = 0.3
GAMMA = 0.99
EPISODES = 10000
QTable = np.zeros((GRID_SIZE,GRID_SIZE,len(ACTIONS)))

In [6]:
def choose_action(state, QTable):
    prob = random.uniform(0,1)
    if prob < EPSILON:
        return random.choice(ACTIONS)
    else:
        return ACTIONS[np.argmax(QTable[state[0]][state[1]])]

In [7]:
def is_valid_state(state):
    if (0 <= state[0] < GRID_SIZE and 
        0 <= state[1] < GRID_SIZE and 
        state not in OBSTACLES):
        return True

In [8]:
def get_next_state(state, action):
    next_state = (state[0]+action[0], state[1]+action[1])
    if is_valid_state(next_state):
        return next_state 
    else:
        return state

In [9]:
def get_reward(state, next_state):
    if next_state == GOAL:
        return 100
    elif next_state in OBSTACLES or next_state == state:
        return -10
    else:
        return -1

In [10]:
def update_q_table(QTable, state, action, reward, next_state):
    action_idx = ACTIONS.index(action)
    QTable[state[0]][state[1]][action_idx] += ALPHA * (reward + GAMMA * np.max(QTable[next_state[0]][next_state[1]]) - QTable[state[0]][state[1]][action_idx])

In [11]:
def agent_is_learning():
    for _ in range(EPISODES):
        state = START
        while state != GOAL:
            action = choose_action(state, QTable)
            next_state = get_next_state(state, action)
            reward = get_reward(state, next_state)
            update_q_table(QTable, state, action, reward, next_state)
            state = next_state
        print("Epoch ",_+1," done.")
    return QTable

In [12]:
QTable = agent_is_learning()

Epoch  1  done.
Epoch  2  done.
Epoch  3  done.
Epoch  4  done.
Epoch  5  done.
Epoch  6  done.
Epoch  7  done.
Epoch  8  done.
Epoch  9  done.
Epoch  10  done.
Epoch  11  done.
Epoch  12  done.
Epoch  13  done.
Epoch  14  done.
Epoch  15  done.
Epoch  16  done.
Epoch  17  done.
Epoch  18  done.
Epoch  19  done.
Epoch  20  done.
Epoch  21  done.
Epoch  22  done.
Epoch  23  done.
Epoch  24  done.
Epoch  25  done.
Epoch  26  done.
Epoch  27  done.
Epoch  28  done.
Epoch  29  done.
Epoch  30  done.
Epoch  31  done.
Epoch  32  done.
Epoch  33  done.
Epoch  34  done.
Epoch  35  done.
Epoch  36  done.
Epoch  37  done.
Epoch  38  done.
Epoch  39  done.
Epoch  40  done.
Epoch  41  done.
Epoch  42  done.
Epoch  43  done.
Epoch  44  done.
Epoch  45  done.
Epoch  46  done.
Epoch  47  done.
Epoch  48  done.
Epoch  49  done.
Epoch  50  done.
Epoch  51  done.
Epoch  52  done.
Epoch  53  done.
Epoch  54  done.
Epoch  55  done.
Epoch  56  done.
Epoch  57  done.
Epoch  58  done.
Epoch  59  done.
Epoch 

In [16]:
def visualize_q_table_as_grid(q_table: np.ndarray) -> None:
    """Visualize the Q-table as a grid with all action values for each state."""
    action_symbols = ['^', '>', 'v', '<']
    
    print("\nDetailed Q-table Grid:")
    
    # Header
    header = "   |" + "|".join(f"   ({i},{j})   " for i in range(GRID_SIZE) for j in range(GRID_SIZE)) + "|"
    print(header)
    print("-" * len(header))

    for action_idx, action_symbol in enumerate(action_symbols):
        row = f" {action_symbol} |"
        for i in range(GRID_SIZE):
            for j in range(GRID_SIZE):
                if (i, j) == GOAL:
                    cell = "   GOAL    "
                elif (i, j) in OBSTACLES:
                    cell = " OBSTACLE  "
                else:
                    q_value = q_table[i, j, action_idx]
                    cell = f" {q_value:9.2f} "
                row += cell + "|"
        print(row)
        print("-" * len(header))

def visualize_best_actions_grid(q_table: np.ndarray) -> None:
    """Visualize the best action and its Q-value for each state in a grid."""
    action_symbols = ['^', '>', 'v', '<']
    
    print("\nBest Actions Grid:")
    header = "-" * (14 * GRID_SIZE + 1)
    print(header)

    for i in range(GRID_SIZE):
        row = "| "
        for j in range(GRID_SIZE):
            if (i, j) == GOAL:
                cell = "   GOAL    "
            elif (i, j) in OBSTACLES:
                cell = " OBSTACLE  "
            else:
                best_action_idx = np.argmax(q_table[i, j])
                best_q_value = q_table[i, j, best_action_idx]
                cell = f"{action_symbols[best_action_idx]}:{best_q_value:7.2f}  "
            row += cell + " | "
        print(row)
        print(header)

In [17]:
# Visualize the Q-table as a grid
visualize_q_table_as_grid(QTable)


Detailed Q-table Grid:
   |   (0,0)   |   (0,1)   |   (0,2)   |   (0,3)   |   (0,4)   |   (0,5)   |   (0,6)   |   (0,7)   |   (0,8)   |   (0,9)   |   (0,10)   |   (0,11)   |   (0,12)   |   (0,13)   |   (0,14)   |   (0,15)   |   (0,16)   |   (0,17)   |   (0,18)   |   (0,19)   |   (0,20)   |   (0,21)   |   (0,22)   |   (0,23)   |   (0,24)   |   (0,25)   |   (0,26)   |   (0,27)   |   (0,28)   |   (0,29)   |   (0,30)   |   (0,31)   |   (0,32)   |   (0,33)   |   (0,34)   |   (0,35)   |   (0,36)   |   (0,37)   |   (0,38)   |   (0,39)   |   (0,40)   |   (0,41)   |   (0,42)   |   (0,43)   |   (0,44)   |   (0,45)   |   (0,46)   |   (0,47)   |   (0,48)   |   (0,49)   |   (0,50)   |   (0,51)   |   (0,52)   |   (0,53)   |   (0,54)   |   (0,55)   |   (0,56)   |   (0,57)   |   (0,58)   |   (0,59)   |   (0,60)   |   (0,61)   |   (0,62)   |   (0,63)   |   (0,64)   |   (0,65)   |   (0,66)   |   (0,67)   |   (0,68)   |   (0,69)   |   (0,70)   |   (0,71)   |   (0,72)   |   (0,73)   |   (0,74)   |   (0,7

In [18]:
# Visualize the best actions and their Q-values in a grid
visualize_best_actions_grid(QTable)


Best Actions Grid:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------